"""initial_schema

Revision ID: cf318d1cffcc
Revises: 
Create Date: 2026-07-17 03:09:49.176553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf318d1cffcc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration to the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INSTRUCTOR',
    sa.Column('InstructorID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=True),
    sa.Column('LastName', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=150), nullable=True),
    sa.Column('Bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('InstructorID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('STUDENT',
    sa.Column('StudentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=True),
    sa.Column('LastName', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=150), nullable=True),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('RegDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('StudentID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('COURSE',
    sa.Column('CourseID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Level', sa.Enum('Beginner', 'Intermediate', 'Advanced', name='course_level'), nullable=True),
    sa.Column('CreatedDate', sa.Date(), nullable=True),
    sa.Column('InstructorID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['InstructorID'], ['INSTRUCTOR.InstructorID'], ),
    sa.PrimaryKeyConstraint('CourseID')
    )
    op.create_table('INSTRUCTOR_LOGIN',
    sa.Column('InstructorLoginID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('InstructorID', sa.Integer(), nullable=True),
    sa.Column('Email', sa.String(length=150), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=True),
    sa.Column('LastLogin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['InstructorID'], ['INSTRUCTOR.InstructorID'], ),
    sa.PrimaryKeyConstraint('InstructorLoginID')
    )
    op.create_table('STUDENT_LOGIN',
    sa.Column('StudentLoginID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StudentID', sa.Integer(), nullable=True),
    sa.Column('Email', sa.String(length=150), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=True),
    sa.Column('LastLogin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['StudentID'], ['STUDENT.StudentID'], ),
    sa.PrimaryKeyConstraint('StudentLoginID')
    )
    op.create_table('CERTIFICATE',
    sa.Column('CertificateID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StudentID', sa.Integer(), nullable=True),
    sa.Column('CourseID', sa.Integer(), nullable=True),
    sa.Column('IssueDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['CourseID'], ['COURSE.CourseID'], ),
    sa.ForeignKeyConstraint(['StudentID'], ['STUDENT.StudentID'], ),
    sa.PrimaryKeyConstraint('CertificateID'),
    sa.UniqueConstraint('StudentID', 'CourseID', name='uq_certificate_student_course')
    )
    op.create_table('ENROLLMENT',
    sa.Column('EnrollmentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StudentID', sa.Integer(), nullable=True),
    sa.Column('CourseID', sa.Integer(), nullable=True),
    sa.Column('EnrollmentDate', sa.Date(), nullable=True),
    sa.Column('CourseStatus', sa.Enum('Active', 'Completed', name='enrollment_status'), nullable=True),
    sa.ForeignKeyConstraint(['CourseID'], ['COURSE.CourseID'], ),
    sa.ForeignKeyConstraint(['StudentID'], ['STUDENT.StudentID'], ),
    sa.PrimaryKeyConstraint('EnrollmentID'),
    sa.UniqueConstraint('StudentID', 'CourseID', name='uq_enrollment_student_course')
    )
    op.create_table('MODULE',
    sa.Column('ModuleID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CourseID', sa.Integer(), nullable=True),
    sa.Column('ModuleTitle', sa.String(length=200), nullable=True),
    sa.Column('ModuleOrder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CourseID'], ['COURSE.CourseID'], ),
    sa.PrimaryKeyConstraint('ModuleID')
    )
    op.create_table('LESSON',
    sa.Column('LessonID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ModuleID', sa.Integer(), nullable=True),
    sa.Column('LessonTitle', sa.String(length=200), nullable=True),
    sa.Column('LessonNumber', sa.Integer(), nullable=True),
    sa.Column('DurationMinutes', sa.Integer(), nullable=True),
    sa.Column('ContentURL', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ModuleID'], ['MODULE.ModuleID'], ),
    sa.PrimaryKeyConstraint('LessonID')
    )
    op.create_table('PROGRESS',
    sa.Column('ProgressID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('StudentID', sa.Integer(), nullable=True),
    sa.Column('LessonID', sa.Integer(), nullable=True),
    sa.Column('ProgressStatus', sa.Enum('Completed', name='progress_status_enum'), nullable=True),
    sa.Column('CompletedTimestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['LessonID'], ['LESSON.LessonID'], ),
    sa.ForeignKeyConstraint(['StudentID'], ['STUDENT.StudentID'], ),
    sa.PrimaryKeyConstraint('ProgressID'),
    sa.UniqueConstraint('StudentID', 'LessonID', name='uq_progress_student_lesson')
    )
    op.drop_index(op.f('Email'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('uq_certificate'), table_name='certificate')
    op.drop_table('certificate')
    op.drop_index(op.f('StudentID'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_table('module')
    op.drop_table('lesson')
    op.drop_index(op.f('Email'), table_name='instructor')
    op.drop_table('instructor')
    op.drop_index(op.f('StudentID'), table_name='progress')
    op.drop_table('progress')
    op.drop_table('course')
    op.drop_index(op.f('uq_instructor_login_email'), table_name='instructor_login')
    op.drop_table('instructor_login')
    op.drop_index(op.f('uq_student_login_email'), table_name='student_login')
    op.drop_table('student_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration from the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_login',
    sa.Column('StudentLoginID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('StudentID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('LastLogin', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['StudentID'], ['student.StudentID'], name=op.f('student_login_ibfk_1')),
    sa.PrimaryKeyConstraint('StudentLoginID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_student_login_email'), 'student_login', ['Email'], unique=True)
    op.create_table('instructor_login',
    sa.Column('InstructorLoginID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('InstructorID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('LastLogin', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['InstructorID'], ['instructor.InstructorID'], name=op.f('instructor_login_ibfk_1')),
    sa.PrimaryKeyConstraint('InstructorLoginID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_instructor_login_email'), 'instructor_login', ['Email'], unique=True)
    op.create_table('course',
    sa.Column('CourseID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Title', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('Description', mysql.TEXT(), nullable=True),
    sa.Column('Level', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('CreatedDate', sa.DATE(), nullable=True),
    sa.Column('InstructorID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("(`Level` in (_utf8mb4'Beginner',_utf8mb4'Intermediate',_utf8mb4'Advanced'))", name='chk_level'),
    sa.ForeignKeyConstraint(['InstructorID'], ['instructor.InstructorID'], name='course_ibfk_1'),
    sa.PrimaryKeyConstraint('CourseID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('progress',
    sa.Column('ProgressID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('StudentID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LessonID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ProgressStatus', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('CompletedTimestamp', mysql.DATETIME(), nullable=True),
    sa.CheckConstraint("(`ProgressStatus` in (_utf8mb4'Completed',_utf8mb4'In Progress'))", name=op.f('chk_progress')),
    sa.ForeignKeyConstraint(['LessonID'], ['lesson.LessonID'], name=op.f('progress_ibfk_2')),
    sa.ForeignKeyConstraint(['StudentID'], ['student.StudentID'], name=op.f('progress_ibfk_1')),
    sa.PrimaryKeyConstraint('ProgressID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('StudentID'), 'progress', ['StudentID', 'LessonID'], unique=True)
    op.create_table('instructor',
    sa.Column('InstructorID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('LastName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Bio', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('InstructorID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('Email'), 'instructor', ['Email'], unique=True)
    op.create_table('lesson',
    sa.Column('LessonID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ModuleID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LessonTitle', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('LessonNumber', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('DurationMinutes', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ContentURL', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ModuleID'], ['module.ModuleID'], name=op.f('lesson_ibfk_1')),
    sa.PrimaryKeyConstraint('LessonID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('module',
    sa.Column('ModuleID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CourseID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ModuleTitle', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('ModuleOrder', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['CourseID'], ['course.CourseID'], name=op.f('module_ibfk_1')),
    sa.PrimaryKeyConstraint('ModuleID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('enrollment',
    sa.Column('EnrollmentID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('StudentID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CourseID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('EnrollmentDate', sa.DATE(), nullable=True),
    sa.Column('CourseStatus', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['CourseID'], ['course.CourseID'], name=op.f('enrollment_ibfk_2')),
    sa.ForeignKeyConstraint(['StudentID'], ['student.StudentID'], name=op.f('enrollment_ibfk_1')),
    sa.PrimaryKeyConstraint('EnrollmentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('StudentID'), 'enrollment', ['StudentID', 'CourseID'], unique=True)
    op.create_table('certificate',
    sa.Column('CertificateID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('StudentID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CourseID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('IssueDate', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['CourseID'], ['course.CourseID'], name=op.f('certificate_ibfk_2')),
    sa.ForeignKeyConstraint(['StudentID'], ['student.StudentID'], name=op.f('certificate_ibfk_1')),
    sa.PrimaryKeyConstraint('CertificateID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_certificate'), 'certificate', ['StudentID', 'CourseID'], unique=True)
    op.create_table('student',
    sa.Column('StudentID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('LastName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('RegDate', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('StudentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('Email'), 'student', ['Email'], unique=True)
    op.drop_table('PROGRESS')
    op.drop_table('LESSON')
    op.drop_table('MODULE')
    op.drop_table('ENROLLMENT')
    op.drop_table('CERTIFICATE')
    op.drop_table('STUDENT_LOGIN')
    op.drop_table('INSTRUCTOR_LOGIN')
    op.drop_table('COURSE')
    op.drop_table('STUDENT')
    op.drop_table('INSTRUCTOR')
    # ### end Alembic commands ###
